2021-06-03 06:46:24,007 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-06-03 06:46:24,629 django.request ERROR    Internal Server Error: /login/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/main/views.py", line 20, in get_login_page
    return render(request, "main/login.html", {})
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register_url' not found. 'register_url' is not a valid view function or pattern name.
2021-06-03 06:46:24,695 django.request WARNING  Not Found: /favicon.ico
2021-06-03 06:46:25,560 django.request ERROR    Internal Server Error: /login/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/main/views.py", line 20, in get_login_page
    return render(request, "main/login.html", {})
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register_url' not found. 'register_url' is not a valid view function or pattern name.
2021-06-03 06:46:35,614 django.request ERROR    Internal Server Error: /login/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/main/views.py", line 20, in get_login_page
    return render(request, "main/login.html", {})
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register_url' not found. 'register_url' is not a valid view function or pattern name.
2021-06-03 06:46:35,624 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 06:46:35,625 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 06:47:02,479 django.request ERROR    Internal Server Error: /login/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/main/views.py", line 20, in get_login_page
    return render(request, "main/login.html", {})
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register_url' not found. 'register_url' is not a valid view function or pattern name.
2021-06-03 06:47:03,023 django.request ERROR    Internal Server Error: /login/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/main/views.py", line 20, in get_login_page
    return render(request, "main/login.html", {})
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register_url' not found. 'register_url' is not a valid view function or pattern name.
2021-06-03 06:47:03,296 django.request ERROR    Internal Server Error: /login/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/main/views.py", line 20, in get_login_page
    return render(request, "main/login.html", {})
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register_url' not found. 'register_url' is not a valid view function or pattern name.
2021-06-03 06:47:03,543 django.request ERROR    Internal Server Error: /login/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/main/views.py", line 20, in get_login_page
    return render(request, "main/login.html", {})
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register_url' not found. 'register_url' is not a valid view function or pattern name.
2021-06-03 06:47:07,802 django.request ERROR    Internal Server Error: /login/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/main/views.py", line 20, in get_login_page
    return render(request, "main/login.html", {})
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register_url' not found. 'register_url' is not a valid view function or pattern name.
2021-06-03 06:47:07,813 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 06:47:07,815 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 06:48:04,344 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 06:48:04,345 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 06:48:09,942 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 06:48:09,944 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 06:48:11,863 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 06:48:11,865 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 06:48:12,927 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 06:48:12,928 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 06:48:13,743 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 06:48:13,745 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 06:48:29,859 django.request ERROR    Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 410, in login
    return LoginView.as_view(**defaults)(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/views.py", line 63, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/views.py", line 92, in form_valid
    auth_login(self.request, form.get_user())
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 132, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 20, in update_last_login
    user.save(update_fields=['last_login'])
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/db/models/base.py", line 801, in save_base
    post_save.send(
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/stanislav/Desktop/web/shop/main/models.py", line 115, in save_user_wallet
    instance.wallet.set_balance(Wallet.max_balance)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 421, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.wallet.RelatedObjectDoesNotExist: User has no wallet.
2021-06-03 06:48:37,630 django.security.csrf WARNING  Forbidden (CSRF token missing or incorrect.): /admin/login/
2021-06-03 06:48:53,779 django.security.csrf WARNING  Forbidden (CSRF token missing or incorrect.): /admin/login/
2021-06-03 06:49:04,411 django.request ERROR    Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 410, in login
    return LoginView.as_view(**defaults)(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/views.py", line 63, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/views.py", line 92, in form_valid
    auth_login(self.request, form.get_user())
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 132, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 20, in update_last_login
    user.save(update_fields=['last_login'])
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/db/models/base.py", line 801, in save_base
    post_save.send(
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/stanislav/Desktop/web/shop/main/models.py", line 115, in save_user_wallet
    instance.wallet.set_balance(Wallet.max_balance)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 421, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.wallet.RelatedObjectDoesNotExist: User has no wallet.
2021-06-03 06:49:21,215 django.request ERROR    Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 410, in login
    return LoginView.as_view(**defaults)(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/views.py", line 63, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/views.py", line 92, in form_valid
    auth_login(self.request, form.get_user())
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 132, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 20, in update_last_login
    user.save(update_fields=['last_login'])
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/db/models/base.py", line 801, in save_base
    post_save.send(
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/stanislav/Desktop/web/shop/main/models.py", line 115, in save_user_wallet
    instance.wallet.set_balance(Wallet.max_balance)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 421, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.wallet.RelatedObjectDoesNotExist: User has no wallet.
2021-06-03 06:49:46,218 django.security.csrf WARNING  Forbidden (CSRF token missing or incorrect.): /admin/login/
2021-06-03 06:49:48,703 django.security.csrf WARNING  Forbidden (CSRF token missing or incorrect.): /admin/login/
2021-06-03 06:49:52,681 django.security.csrf WARNING  Forbidden (CSRF token missing or incorrect.): /admin/login/
2021-06-03 06:50:00,895 django.request ERROR    Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 410, in login
    return LoginView.as_view(**defaults)(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/views.py", line 63, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/views.py", line 92, in form_valid
    auth_login(self.request, form.get_user())
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 132, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 20, in update_last_login
    user.save(update_fields=['last_login'])
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/db/models/base.py", line 801, in save_base
    post_save.send(
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/stanislav/Desktop/web/shop/main/models.py", line 115, in save_user_wallet
    instance.wallet.set_balance(Wallet.max_balance)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 421, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.wallet.RelatedObjectDoesNotExist: User has no wallet.
2021-06-03 06:53:33,305 django.security.csrf WARNING  Forbidden (CSRF token missing or incorrect.): /admin/login/
2021-06-03 06:53:35,640 django.security.csrf WARNING  Forbidden (CSRF token missing or incorrect.): /admin/login/
2021-06-03 06:53:49,876 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 06:53:49,878 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 06:54:19,786 django.request ERROR    Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 410, in login
    return LoginView.as_view(**defaults)(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/views.py", line 63, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/views.py", line 92, in form_valid
    auth_login(self.request, form.get_user())
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 132, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 20, in update_last_login
    user.save(update_fields=['last_login'])
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/db/models/base.py", line 801, in save_base
    post_save.send(
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/stanislav/Desktop/web/shop/main/models.py", line 115, in save_user_wallet
    instance.wallet.set_balance(Wallet.max_balance)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 421, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.wallet.RelatedObjectDoesNotExist: User has no wallet.
2021-06-03 06:55:14,785 django.utils.autoreload INFO     /Users/stanislav/Desktop/web/shop/main/models.py changed, reloading.
2021-06-03 06:55:14,786 asyncio      DEBUG    Using selector: KqueueSelector
2021-06-03 06:55:15,329 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-06-03 06:55:15,808 django.security.csrf WARNING  Forbidden (CSRF token missing or incorrect.): /admin/login/
2021-06-03 06:55:17,739 django.security.csrf WARNING  Forbidden (CSRF token missing or incorrect.): /admin/login/
2021-06-03 06:55:21,783 asyncio      DEBUG    Using selector: KqueueSelector
2021-06-03 06:55:36,191 asyncio      DEBUG    Using selector: KqueueSelector
2021-06-03 06:55:44,342 asyncio      DEBUG    Using selector: KqueueSelector
2021-06-03 06:55:49,523 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-06-03 06:56:04,597 django.request WARNING  Not Found: /favicon.ico
2021-06-03 06:56:56,991 django.request WARNING  Not Found: /favicon.ico
2021-06-03 06:57:22,495 django.request WARNING  Not Found: /favicon.ico
2021-06-03 06:58:24,262 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 06:58:24,264 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 07:02:08,511 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 07:02:08,512 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 07:02:10,038 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 07:02:10,040 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 07:02:10,286 django.request ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/main/views.py", line 12, in get_main_page
    return render(request, "main/main.html", {})
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user_profile_url' not found. 'user_profile_url' is not a valid view function or pattern name.
2021-06-03 07:02:10,389 django.request ERROR    Internal Server Error: /categories/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/main/views.py", line 51, in get_categories
    return render(request, "main/categories.html", {'categories': categories})
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user_profile_url' not found. 'user_profile_url' is not a valid view function or pattern name.
2021-06-03 07:04:15,366 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 07:04:15,370 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 07:04:37,247 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 07:04:37,248 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 07:05:20,572 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 07:05:20,574 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 07:05:26,406 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 07:05:26,408 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 07:06:05,572 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 07:06:05,574 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 07:06:43,777 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 07:06:43,780 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 07:07:18,198 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 07:07:18,200 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 07:11:01,054 django.utils.autoreload INFO     /Users/stanislav/Desktop/web/shop/main/views.py changed, reloading.
2021-06-03 07:11:01,055 asyncio      DEBUG    Using selector: KqueueSelector
2021-06-03 07:11:01,636 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-06-03 07:11:39,317 django.utils.autoreload INFO     /Users/stanislav/Desktop/web/shop/main/views.py changed, reloading.
2021-06-03 07:11:39,318 asyncio      DEBUG    Using selector: KqueueSelector
2021-06-03 07:11:39,784 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-06-03 07:11:45,764 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 07:11:45,771 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 07:11:53,017 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 07:11:53,019 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 07:14:34,537 django.utils.autoreload INFO     /Users/stanislav/Desktop/web/shop/main/views.py changed, reloading.
2021-06-03 07:14:34,538 asyncio      DEBUG    Using selector: KqueueSelector
2021-06-03 07:14:34,954 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-06-03 07:15:07,601 django.utils.autoreload INFO     /Users/stanislav/Desktop/web/shop/main/views.py changed, reloading.
2021-06-03 07:15:07,601 asyncio      DEBUG    Using selector: KqueueSelector
2021-06-03 07:15:07,995 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-06-03 07:15:29,527 django.utils.autoreload INFO     /Users/stanislav/Desktop/web/shop/main/views.py changed, reloading.
2021-06-03 07:15:29,528 asyncio      DEBUG    Using selector: KqueueSelector
2021-06-03 07:15:29,886 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-06-03 07:16:39,095 django.utils.autoreload INFO     /Users/stanislav/Desktop/web/shop/main/views.py changed, reloading.
2021-06-03 07:16:39,095 asyncio      DEBUG    Using selector: KqueueSelector
2021-06-03 07:16:39,461 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-06-03 07:16:47,059 django.security.csrf WARNING  Forbidden (CSRF token missing or incorrect.): /login/
2021-06-03 07:17:07,157 django.utils.autoreload INFO     /Users/stanislav/Desktop/web/shop/main/views.py changed, reloading.
2021-06-03 07:17:07,157 asyncio      DEBUG    Using selector: KqueueSelector
2021-06-03 07:17:07,501 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-06-03 07:17:13,917 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 07:17:13,919 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 07:25:37,378 django.utils.autoreload INFO     /Users/stanislav/Desktop/web/shop/main/urls.py changed, reloading.
2021-06-03 07:25:37,378 asyncio      DEBUG    Using selector: KqueueSelector
2021-06-03 07:25:38,060 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-06-03 07:32:16,044 django.utils.autoreload INFO     /Users/stanislav/Desktop/web/shop/main/views.py changed, reloading.
2021-06-03 07:32:16,045 asyncio      DEBUG    Using selector: KqueueSelector
2021-06-03 07:32:16,455 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-06-03 07:33:20,172 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 07:33:20,178 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 07:33:21,877 django.request WARNING  Not Found: /favicon.ico
2021-06-03 07:33:39,838 django.utils.autoreload INFO     /Users/stanislav/Desktop/web/shop/main/urls.py changed, reloading.
2021-06-03 07:33:39,838 asyncio      DEBUG    Using selector: KqueueSelector
2021-06-03 07:33:40,235 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-06-03 07:33:40,789 django.request ERROR    Internal Server Error: /registration/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: main/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/main/views.py", line 103, in get_registration_page
    return render(request, 'main/registration.html', {'form': user_form, 'profile_form': profile_form})
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: main/base.html
2021-06-03 07:33:41,684 django.request ERROR    Internal Server Error: /registration/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: main/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/main/views.py", line 103, in get_registration_page
    return render(request, 'main/registration.html', {'form': user_form, 'profile_form': profile_form})
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: main/base.html
2021-06-03 07:33:45,805 django.request ERROR    Internal Server Error: /registration/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: main/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/main/views.py", line 103, in get_registration_page
    return render(request, 'main/registration.html', {'form': user_form, 'profile_form': profile_form})
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: main/base.html
2021-06-03 07:33:50,247 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 07:33:50,250 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 07:33:52,231 django.request ERROR    Internal Server Error: /registration/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: main/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanislav/Desktop/web/shop/main/views.py", line 103, in get_registration_page
    return render(request, 'main/registration.html', {'form': user_form, 'profile_form': profile_form})
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: main/base.html
2021-06-03 09:45:25,917 django.request ERROR    Internal Server Error: /products/milk/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view main.views.get_specific_product didn't return an HttpResponse object. It returned None instead.
2021-06-03 09:45:25,976 django.request WARNING  Not Found: /favicon.ico
2021-06-03 09:45:37,458 django.request ERROR    Internal Server Error: /products/biscuits/
Traceback (most recent call last):
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/stanislav/Desktop/web/shop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view main.views.get_specific_product didn't return an HttpResponse object. It returned None instead.
2021-06-03 09:46:05,810 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 09:46:05,812 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 09:46:17,974 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 09:46:17,978 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 09:46:31,320 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 09:46:31,322 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 09:46:34,685 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 09:46:34,687 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
2021-06-03 09:46:46,996 django.request WARNING  Not Found: /login/css/style.css
2021-06-03 09:46:46,998 django.request WARNING  Not Found: /login/path/to/font-awesome/css/font-awesome.min.css
